name: kline_chart
description: flutter kline chart plugin, support multiple indicators, MA, EMA, VOL, BOLL, KDJ, RSI, WR, OBV
version: 0.0.1+3

homepage: https://github.com/AscenX/kline_chart
repository: https://github.com/AscenX/kline_chart


environment:
  sdk: ^2.17.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
